name: Build and Release HEX

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build project
        run: platformio run

      - name: Find HEX files
        run: |
          mkdir -p hexfiles
          find .pio/build -name "*.hex" -exec cp {} hexfiles/ \;

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: hexfiles/*.hex
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}